spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-idle-time: 30m
      max-life-time: 1h
      max-size: 20
  sql:
    init:
      mode: always
      platform: r2dbc
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: false
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

management:
  health:
    db:
      enabled: false
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.r2dbc.core: info
server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: false

llm:
  api:
    gemini:
      key: ${GEMINI_API_KEY}
    gpt:
      key: ${GPT_API_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

auth:
  token:
    expiration: ${ACCESS_EXP}
  paths: /api/v1/user/profile,/api/v1/auth/logout,/api/v1/admin,/api/v1/questions,/api/v1/terms,/api/v1/contributions,/api/v1/donations

scheduler:
  key: ${SCHEDULER_KEY}