spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;
    username: sa
    password:
  sql:
    init:
      mode: always  # 스키마 자동 생성
      platform: r2dbc
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

  management:
    health:
      db:
        enabled: false
      redis:
        enabled: false
    endpoints:
      web:
        exposure:
          include: prometheus, health, info
    metrics:
      tags:
        application: ${spring.application.name}

  logging:
    level:
      org.springframework.r2dbc.core: debug
  server:
    port: 8081

  springdoc:
    swagger-ui:
      path: /swagger-ui/swagger-ui.html
      operationsSorter: method
      disable-swagger-default-url: true
      display-request-duration: true
    api-docs:
      path: /swagger-ui/api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

llm:
  api:
    gemini:
      key: ${GEMINI_API_KEY}
    gpt:
      key: ${GPT_API_KEY}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

  auth:
    token:
      expiration: ${ACCESS_EXP}
    paths: ${AUTH_PATHS}

scheduler:
  key: ${SCHEDULER_KEY}