spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
      platform: r2dbc
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: false
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}

management:
  health:
    db:
      enabled: false
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.r2dbc.core: info
server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: false

llm:
  api:
    key: ${LLM_API_KEY}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

auth:
  token:
    expiration: ${ACCESS_EXP}
  paths: ${AUTH_PATHS}