package com.csforever.app.question.model

enum class QuestionTag(val displayName: String) {
    SPRING("Spring"),
    NODE_JS("NodeJS"),
    ASP_NET("ASP.Net"),
    REACT("React"),
    NOSQL("NoSql"),
    RDB("RDB"),
    JAVA("Java"),
    C_SHARP("C#"),
    JAVA_SCRIPT("JavaScript"),
    OS("OS"),
    ALGORITHM("Algorithm"),
    DATA_STRUCTURE("Data Structure"),
    NETWORK("Network"),
    DESIGN_PATTERN("Design Pattern"),
    SW_ENGINEERING("SW Engineering"),
    DEVOPS("DevOps"),
    PYTHON("Python"),
    R("R"),
    C_PLUS_PLUS("C++"),
    UNITY("Unity"),
    KUBERNETES("Kubernetes"),
    KAFKA("Kafka"),
    MSA("MSA"),
    FLUTTER("Flutter"),
    AI("AI"),
    ;
}